-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id text NOT NULL,
  user_id uuid,
  event_type text NOT NULL,
  path text,
  referrer text,
  source text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  duration integer DEFAULT 0,
  geo_country text,
  geo_city text,
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.app_settings (
  id integer NOT NULL DEFAULT 1,
  slogan text,
  secondary_slogan text,
  mission text,
  vision text,
  core_values text,
  contact_email text,
  contact_phone text,
  contact_address text,
  social_links jsonb DEFAULT '{}'::jsonb,
  currency text DEFAULT 'GBP'::text,
  tax_rate numeric DEFAULT 20.0,
  free_shipping_threshold numeric,
  business_hours jsonb,
  shipping_policy text,
  return_policy text,
  privacy_policy text,
  terms_conditions text,
  hero_banner_image text,
  hero_banner_text text,
  featured_categories jsonb,
  announcement_text text,
  is_announcement_enabled boolean DEFAULT false,
  support_email text,
  maintenance_mode boolean DEFAULT false,
  maintenance_message text,
  seo_title text,
  seo_description text,
  shop_seo_title text,
  shop_seo_description text,
  blog_seo_title text,
  blog_seo_description text,
  about_seo_title text,
  about_seo_description text,
  enable_email_notifications boolean DEFAULT true,
  enable_email_welcome boolean DEFAULT true,
  enable_email_new_order boolean DEFAULT true,
  enable_email_order_shipped boolean DEFAULT true,
  founder_name text,
  founder_bio text,
  founder_image text,
  founder_quote text,
  logo_image text,
  enable_newsletter_signup boolean DEFAULT true,
  enable_contact_form boolean DEFAULT true,
  enable_reviews boolean DEFAULT true,
  require_login_for_checkout boolean DEFAULT false,
  paypal_client_id text,
  paypal_mode text DEFAULT 'sandbox'::text,
  payment_gateway_enabled boolean DEFAULT false,
  enable_email_admin_new_order boolean DEFAULT true,
  enable_email_contact_admin boolean DEFAULT true,
  paypal_secret_key text,
  google_analytics_id text,
  custom_head_scripts text,
  default_og_image text,
  gemini_api_key text,
  resend_api_key text,
  sender_email text,
  resend_from_email text DEFAULT 'onboarding@resend.dev'::text,
  paypal_webhook_id text,
  enable_featured_products boolean DEFAULT true,
  enable_commitment_section boolean DEFAULT true,
  enable_categories_section boolean DEFAULT true,
  enable_community_section boolean DEFAULT true,
  enable_journal_section boolean DEFAULT true,
  enable_social_section boolean DEFAULT true,
  priority_pages jsonb,
  seo_content_title text,
  seo_content_intro text,
  seo_content_col1_title text,
  seo_content_col1_body text,
  seo_content_col2_title text,
  seo_content_col2_body text,
  social_section_title text,
  social_section_body text,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.blog_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  CONSTRAINT blog_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment text NOT NULL,
  is_approved boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_comments_pkey PRIMARY KEY (id),
  CONSTRAINT blog_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.blog_posts(id),
  CONSTRAINT blog_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.blog_post_tags (
  blog_post_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  CONSTRAINT blog_post_tags_pkey PRIMARY KEY (blog_post_id, tag_id),
  CONSTRAINT blog_post_tags_blog_post_id_fkey FOREIGN KEY (blog_post_id) REFERENCES public.blog_posts(id),
  CONSTRAINT blog_post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.blog_tags(id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  summary text,
  content text NOT NULL,
  thumbnail text,
  date date DEFAULT CURRENT_DATE,
  author text,
  slug text UNIQUE,
  featured_image text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  category_id uuid,
  seo_title text,
  seo_description text,
  view_count integer DEFAULT 0,
  reading_time integer,
  updated_at timestamp with time zone DEFAULT now(),
  canonical_url text,
  is_noindex boolean DEFAULT false,
  is_nofollow boolean DEFAULT false,
  keywords ARRAY,
  scheduled_for timestamp with time zone,
  likes integer NOT NULL DEFAULT 0,
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.blog_categories(id)
);
CREATE TABLE public.blog_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  CONSTRAINT blog_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  product_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  selected_size text,
  selected_color text,
  added_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.categories (
  key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL,
  bg_class text NOT NULL,
  seo_title text,
  seo_description text,
  canonical_url text,
  is_noindex boolean DEFAULT false,
  CONSTRAINT categories_pkey PRIMARY KEY (key)
);
CREATE TABLE public.contact_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  subject text,
  message text NOT NULL,
  phone text,
  is_read boolean DEFAULT false,
  replied_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_submissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discount_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  description text,
  discount_type text CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  minimum_purchase numeric,
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  max_uses integer,
  times_used integer DEFAULT 0,
  is_active boolean DEFAULT true,
  applicable_categories ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  subject text NOT NULL,
  body_html text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.newsletter_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text,
  is_subscribed boolean DEFAULT true,
  subscribed_at timestamp with time zone DEFAULT now(),
  unsubscribed_at timestamp with time zone,
  source text DEFAULT 'website'::text,
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  products jsonb NOT NULL,
  total numeric NOT NULL,
  status text DEFAULT 'Pending'::text CHECK (status = ANY (ARRAY['Pending'::text, 'Processing'::text, 'Shipped'::text, 'Delivered'::text, 'Cancelled'::text, 'Refunded'::text, 'Pending Payment'::text, 'Return Requested'::text, 'Return Approved'::text, 'Return Rejected'::text, 'Returned'::text])),
  date timestamp with time zone DEFAULT now(),
  order_number text UNIQUE,
  payment_method text,
  payment_status text DEFAULT 'pending_payment'::text CHECK (payment_status = ANY (ARRAY['paid'::text, 'unpaid'::text, 'pending'::text, 'failed'::text, 'refunded'::text])),
  payment_intent_id text,
  tracking_number text,
  notes text,
  discount_code text,
  discount_amount numeric DEFAULT 0,
  subtotal numeric,
  tax_amount numeric DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  refunded_at timestamp with time zone,
  shipping_address jsonb,
  customer_email text,
  customer_name text,
  return_reason text,
  return_requested_at timestamp with time zone,
  return_status text DEFAULT 'none'::text CHECK (return_status = ANY (ARRAY['none'::text, 'requested'::text, 'approved'::text, 'rejected'::text, 'completed'::text])),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  user_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text,
  verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  category_key text,
  description text,
  sizes ARRAY,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  sku text,
  stock_quantity integer DEFAULT 100 CHECK (stock_quantity >= 0),
  low_stock_threshold integer DEFAULT 5,
  weight numeric,
  colors ARRAY,
  tags ARRAY,
  sale_price numeric,
  is_on_sale boolean DEFAULT false,
  is_published boolean DEFAULT true,
  seo_title text,
  seo_description text,
  slug text UNIQUE,
  total_sales integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  review_count integer DEFAULT 0,
  images ARRAY,
  canonical_url text,
  is_noindex boolean DEFAULT false,
  is_nofollow boolean DEFAULT false,
  keywords ARRAY,
  is_free_shipping boolean DEFAULT false,
  shipping_class text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_key_fkey FOREIGN KEY (category_key) REFERENCES public.categories(key)
);
CREATE TABLE public.shipping_options (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  zone_id uuid,
  name text NOT NULL,
  rate numeric NOT NULL DEFAULT 0,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipping_options_pkey PRIMARY KEY (id),
  CONSTRAINT shipping_options_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.shipping_zones(id)
);
CREATE TABLE public.shipping_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  countries ARRAY NOT NULL,
  base_rate numeric NOT NULL,
  per_kg_rate numeric,
  free_shipping_threshold numeric,
  estimated_days text,
  is_active boolean DEFAULT true,
  CONSTRAINT shipping_zones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_addresses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  label text NOT NULL DEFAULT 'Home'::text,
  address1 text NOT NULL,
  address2 text,
  city text NOT NULL,
  postcode text NOT NULL,
  country text NOT NULL DEFAULT 'United Kingdom'::text,
  phone text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT user_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  email text NOT NULL UNIQUE CHECK (email ~* '^.+@.+\..+$'::text),
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['admin'::text, 'user'::text])),
  created_at timestamp with time zone DEFAULT now(),
  avatar_url text,
  bio text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wishlists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  product_id uuid,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlists_pkey PRIMARY KEY (id),
  CONSTRAINT wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT wishlists_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);